### ISSUE TITLE
Django 1.10 support?

### ISSUE THREAD

**Issue by manikos** [staticdev/django-pagination-bootstrap#18]
Since I upgraded my project to Django 1.10 and changed the setting from `MIDDLEWARE_CLASSES` to `MIDDLEWARE` I get an error due to the lack of the adaptation of the new MIDDLEWARE style.

The error is thrown from file `django/core/handlers/base.py", line 82, in load_middleware` and it says: `mw_instance = middleware(handler)` TypeError: object() takes no parameters`.

It is clearly a middleware issue. Should this be fixed?

**Comment by urtzai** [comment]
Here I made the fix: #19

**Comment by manikos** [comment]
Great! Thank you very much!!

**Comment by staticdev** [comment]
I drop support for 1.6 and added the support for 1.10 on TravisCI. Also merged @urtzai #19 pull request for that.

**Comment by staticdev** [comment]
I also created #20 since I failed to make Tox integration to test the new supported environments on Travis.
