### ISSUE TITLE
'NoneType' object has no attribute 'page_range'

### ISSUE THREAD

**Issue by shadiakiki1986** [staticdev/django-pagination-bootstrap#28]
When I updated to version 1.2.1 of django-pagination-bootstrap, I started getting the error in the title.

[Here](http://pastebin.com/GKvSrJwW) is the complete traceback.

It seems that [context['paginator']](https://github.com/staticdev/django-pagination-bootstrap/blob/master/pagination_bootstrap/templatetags/pagination_tags.py#L156) is returning `None`

Edit 1: version 1.2 did not have this issue, i.e. workaround: `pip install -U django-pagination-bootstrap==1.2`

Edit 2: How can I find which commit was version 1.2? The git repository doesn't have any tags, but pypi has them

**Comment by staticdev** [comment]
@shadiakiki1986 I'm not used to using tags, maybe I should. But if you see the commits list, I always make a commit on version.py write before I pack it to PyPi.

**Comment by staticdev** [comment]
@shadiakiki1986 I started using tags from now on. But you can track the change in the Commits list on Github looking at version.py file changes.

**Comment by staticdev** [comment]
@shadiakiki1986 I am closing the issue assuming it was fixed in 1.2.4 version.
