### ISSUE TITLE
Python 2/3 exception handling

### ISSUE THREAD

**Issue by marts** [staticdev/django-pagination-bootstrap#6]
Hello, there are a couple changes in this fork that would be really great to make the code python 3 compatible. Any chance of incorporating?

https://github.com/jcarbaugh/django-pagination-bootstrap/commit/44d3d99dc99dda599d2e5bdd8e4a9849ad6ad0e5
https://github.com/jcarbaugh/django-pagination-bootstrap/commit/a78565575a78cf5d8cb06d387f3af0901d717594

**Comment by staticdev** [comment]
Sorry marts but the links provided are giving 404 error. Merge #7 had some changes in the expection handling, so I will consider this issue solved.

**Comment by marts** [comment]
LGTM
