### ISSUE TITLE
Testing needed

### ISSUE THREAD

**Issue by staticdev** [staticdev/django-pagination-bootstrap#9]
Pull requests #7 and #8 were merged for compatibility with Django 1.9 and Python 3. Although, testing is needed for it to get a new version in PyPI.

Any help would be very appreciated.

**Comment by avelis** [comment]
@staticdev Looking into it briefly.

Would you be open to using TravisCI for testing automation? This would require you setting it up with travisci.org. The other alternative I know of is using tox.

Now that describes how to run tests. The real work would have to convert the `tests.py` file into actionable assertions. Either I wanted to gain some insights into what you had in mind and start the dialogue on it.

**Comment by avelis** [comment]
Also thanks for creating this library.

**Comment by staticdev** [comment]
@avelis I've never heard of TravisCI, but yes I am open to it. Already synced in the website and enabled this repo. I think I need to put the .travis.yml . Are you experienced with that? If you make a pull request for that, I think it would save me some time.. I can help whenever possible.

**Comment by avelis** [comment]
@staticdev I will take a look on adding a travisci yml file in a pull-request.

**Comment by avelis** [comment]
@staticdev To help me better under stand what to create and configure with TravisCI how were you running the actual tests.py file? Was it a doctest?

**Comment by staticdev** [comment]
The tests.py file was inherited from the original lib.. it need to be refactored.

**Comment by staticdev** [comment]
As testing was refactored and build passes on TravisCI, I will consider this issue handled.
Thanks for @avelis contribution.
